name: git-hub-action

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: TFLint Version
        run: tflint --version

      - name: TFLint Init
        run: tflint --init

      - name: Run TFLint
        run: tflint  

  deploy:
    needs: security
    runs-on: self-hosted

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        run: az login --service-principal --username 9582628e-5f25-4692-9431-a531a95b0e92 --password D168Q~o_abZSmiQgSa_vZk.mv7XW0J_dSBfzwbax --tenant b35ae60b-af62-44bb-a839-c1563125ea80

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan 

      - name: Terraform Apply
        run: terraform apply -auto-approve 