# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      # Runs a set of commands using the runners shell ti azre login    
      - name: Azure Login
        uses: Azure/login@v3
        with:
          # creds: kLM8Q~LLBUrfQbyZqKGY2GwaK1oveMGJav3kJasS
          client-id: 9582628e-5f25-4692-9431-a531a95b0e92
          tenant-id: b35ae60b-af62-44bb-a839-c1563125ea80
          subscription-id: 934f0ced-05a0-41ba-8687-01cd039c4deb
      # Set this value to true to enable Azure PowerShell Login in addition to Azure CLI login
          enable-AzPSSession: # optional
      # Name of the environment. Supported values are azurecloud, azurestack, azureusgovernment, azurechinacloud, azuregermancloud. Default being azurecloud
          environment: # optional, default is azurecloud
      # St this value to true to enable support for accessing tenants without subscriptions
          allow-no-subscriptions: # optional
      # Provide audience field for access-token. Default value is api://AzureADTokenExchange
          audience: # optional, default is api://AzureADTokenExchange
      # The type of authentication. Supported values are SERVICE_PRINCIPAL, IDENTITY. Default value is SERVICE_PRINCIPAL
          auth-type: # optional, default is SERVICE_PRINCIPAL
            
